server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 10

spring:
  application:
    name: zmqc
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      max-lifetime: 30000
      maximum-pool-size: 100
      pool-name: HikariPC
      idle-timeout: 30000
      auto-commit: true
      connection-timeout: 50000
      connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    datacenter-id: 1
    worker-id: 1
    db-config:
      id-type: id_worker
      insert-strategy: not_empty
      update-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
