server:
  #服务端口号
  port: 80
  #服务初始路径
  servlet:
    context-path: /
  #tomcat参数
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 30
    connection-timeout: 5000
---
spring:
  #服务名称
  application:
    name: zmqc-admin
  #静态资源访问路径
  mvc:
    static-path-pattern: /static/**
  #数据库配置
  datasource:
    url: jdbc:mysql://114.55.96.66:8066/zmqc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    #druid 数据源配置
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: root
        login-password: root
      filter:
        stat:
          log-slow-sql: true
      name: druidDataSource
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #redis配置
  redis:
    host: 47.98.38.211
    password: redis
    database: 0
    port: 6688
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 3s
  #前端框架
  thymeleaf:
    encoding: UTF-8
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
  # 开启热部署
  devtools:
    restart:
      enabled: true
    add-properties: true
---
#数据库查询框架
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
---
logging:
  level:
    work.chenbo.zmcq.admin.business: debug